/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary-fixed-dim": "#474746",
                "primary-fixed": "#5f5e5e",
                "secondary-container": "#d4d4d4",
                "surface-container-high": "#e8e8e8",
                "outline-variant": "#c6c6c6",
                "on-primary-fixed": "#ffffff",
                "surface-bright": "#f9f9f9",
                "on-error": "#ffffff",
                "primary": "#000000",
                "secondary-fixed": "#c6c6c7",
                "surface": "#f9f9f9",
                "on-primary-fixed-variant": "#e5e2e1",
                "inverse-primary": "#c8c6c5",
                "tertiary-fixed": "#006d36",
                "on-surface-variant": "#474747",
                "on-primary": "#e5e2e1",
                "surface-container-low": "#f3f3f3",
                "primary-container": "#3c3b3b",
                "inverse-on-surface": "#f1f1f1",
                "error": "#ba1a1a",
                "surface-dim": "#dadada",
                "on-tertiary-fixed-variant": "#83fba5",
                "surface-container-highest": "#e2e2e2",
                "on-secondary-fixed-variant": "#3a3c3c",
                "tertiary-container": "#008644",
                "on-secondary-fixed": "#1a1c1c",
                "on-secondary-container": "#1a1c1c",
                "surface-container": "#eeeeee",
                "background": "#f9f9f9",
                "tertiary": "#004520",
                "on-tertiary": "#83fba5",
                "tertiary-fixed-dim": "#005227",
                "on-primary-container": "#ffffff",
                "error-container": "#ffdad6",
                "on-error-container": "#410002",
                "on-secondary": "#ffffff",
                "on-background": "#1a1c1c",
                "on-surface": "#1a1c1c",
                "surface-tint": "#5f5e5e",
                "secondary-fixed-dim": "#aaabab",
                "outline": "#777777",
                "surface-container-lowest": "#ffffff",
                "on-tertiary-fixed": "#ffffff",
                "secondary": "#5d5f5f",
                "surface-variant": "#e2e2e2",
                "inverse-surface": "#2f3131",
                "on-tertiary-container": "#ffffff"
            },
            fontFamily: {
                "headline": ["Noto Serif"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px" },
        },
    },
    plugins: [],
}